<a href="https://colab.research.google.com/github/jchen8000/MachineLearning/blob/master/7%20K-Nearest%20Neighbors/KNN_Algorithm_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# K-Nearest Neighbors Algorithm and Implementation


In [ ]:
%pip install \
  numpy==2.0.2 \
  scikit-learn==1.6.1 \
  scipy==1.16.3

## Algorithm

Suppose:

> There are dataset $x^{(1)}, x^{(2)},...,x^{(n)}$, 
> and the labels $y^{(1)}, y^{(2)},...,y^{(n)}$
>
> there are $n$ data points in the dataset
>
> there is a new data point $x_{new}$

<br>

There are five steps for KNN

1.$\; $Select a $k$ as the number of neighbors.

2.$\; $Calculate the distances from the new data point $x_{new}$ to each data points $x^{(i)}$, where $i \in [1,n]$

> Euclidean Distance function, see below, is used for calculating the distance.
> The calculated distance is an array of size $n$.
```
def _euclidean(a, b):
    return np.sqrt(np.sum((a - b)**2, axis=1))
distances = _euclidean(X, x_new)
```

3.$\; $Sort the calculated distances in ascending order, and get top $k$ items from the sorted distances.

> The distances are sorted from small to large.
>
> The $k$ items are the nearest neighbors.
>
> Get the indices of the $k$ nearest neighbors.
```
kneighbors = np.argsort(distances)[:k]
```

4.$\; $Get the labels of the $k$ nearest neighbors by their indices.

>```
labels = self.y[kneighbors]
>```

5.$\; $Assign the new data point to the class with the most items from the classes of the $k$ nearest neighbors.

> For example, the labels of the $k$ nearest neighbors are [0, 0, 1, 2, 2, 2 2], then assign 2 to the new data point because 2 is the most items.
```
pred = scipy.stats.mode(labels)[0]
```

**Euclidean Distance function**

Euclidean Distance function is used to calculate the distances in Step 2.

In $2$-dimensional space, there are two vectors: $v = (x_1, y_1)$ and $u = (x_2, y_2)$, 

The Euclidean distance between $v$ and $u$ is:

$\quad d(u,v) = \parallel u-v \parallel = \sqrt{(x_2-x_1)^2+(y_2-y_1)^2}$

<br>

In $n$-dimensional space there are vectors: $v = (v_1, v_2, ... , v_n)$ and $u =(u_1, u_2, ..., u_n)$, 

The Euclidean distance between $v$ and $u$ is:

$\quad d(u,v) = \parallel u-v \parallel = \sqrt{(u_1-v_1)^2+(u_2-v_2)^2+...+(u_n-v_n)^2}$

```
def _euclidean(a, b):
    return np.sqrt(np.sum((a - b)**2, axis=1))
```

## Implementation from Scratch

In [1]:
import numpy as np
from scipy import stats
from sklearn import model_selection
from sklearn import datasets
from sklearn import metrics

In [2]:
class KNN:
    def __init__(self, k):
        #Step 1: select k
        self.k = k

    def _euclidean(self, a, b):
        return np.sqrt(np.sum((a - b)**2, axis=1))

    def fit(self, X, y):
        self.X = X
        self.y = y

    def predict(self, X):
        pred = []
        for x in X:
            #Step 2: calculate distances 
            distances = self._euclidean(self.X, x)
            #Step 3: sort distances
            kneighbors = np.argsort(distances)[:k]
            #Step 4: get labels of k nearest neighbors
            labels = self.y[kneighbors]
            #Step 5: assign the most labels to new data
            pred.append( stats.mode(labels)[0] )
        return np.array(pred).reshape(-1, )

## Datasets

In [3]:
iris= datasets.load_iris()
X_train, X_test, y_train, y_test = \
model_selection.train_test_split(iris.data, 
                                 iris.target, 
                                 train_size = .75, 
                                 random_state=0)
k = 7
knn = KNN(k)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
a_score = metrics.accuracy_score(y_test, y_pred)
c_matrix = metrics.confusion_matrix(y_test, y_pred)
c_report = metrics.classification_report(y_test, y_pred)
print("Accuracy Score:\n", a_score)
print("Confusion matrix:\n", c_matrix)
print("Classification Report:\n", c_report)

Accuracy Score:
 0.9736842105263158
Confusion matrix:
 [[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38



In [4]:
digits = datasets.load_digits()
X2_train, X2_test, y2_train, y2_test = \
model_selection.train_test_split(digits.data, 
                                 digits.target, 
                                 train_size = .75, 
                                 random_state=0)
k = 1
knn2 = KNN(k)
knn2.fit(X2_train, y2_train)
y2_pred = knn2.predict(X2_test)
a2_score = metrics.accuracy_score(y2_test, y2_pred)
c2_matrix = metrics.confusion_matrix(y2_test, y2_pred)
c2_report = metrics.classification_report(y2_test, y2_pred)
print("Accuracy Score:\n", a2_score)
print("Confusion matrix:\n", c2_matrix)
print("Classification Report:\n", c2_report)

Accuracy Score:
 0.9911111111111112
Confusion matrix:
 [[37  0  0  0  0  0  0  0  0  0]
 [ 0 43  0  0  0  0  0  0  0  0]
 [ 0  0 43  1  0  0  0  0  0  0]
 [ 0  0  0 45  0  0  0  0  0  0]
 [ 0  0  0  0 38  0  0  0  0  0]
 [ 0  0  0  0  0 47  0  0  0  1]
 [ 0  0  0  0  0  0 52  0  0  0]
 [ 0  0  0  0  0  0  0 48  0  0]
 [ 0  0  0  0  0  0  0  0 48  0]
 [ 0  0  0  1  0  1  0  0  0 45]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       1.00      1.00      1.00        43
           2       1.00      0.98      0.99        44
           3       0.96      1.00      0.98        45
           4       1.00      1.00      1.00        38
           5       0.98      0.98      0.98        48
           6       1.00      1.00      1.00        52
           7       1.00      1.00      1.00        48
           8       1.00      1.00      1.00        48
           9       0.98      0.96      0.97      