<a href="https://colab.research.google.com/github/jchen8000/MachineLearning/blob/master/0%20Math%20Fondamental/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


# 1. Matrices

## 1.1 An example of a matrix.

A matrix is a rectangular, or square, array of numbers, expressions, or symbols, which are arranged in rows and columns. If a matrix has $m$ rows and $n$ columns, it's called a $m \times n$ matrix.

$\space $

As an example: 

$ A = \begin{bmatrix}3&8&5&12\\-5&28&3&10\\6&2&15&3\end{bmatrix} $

This matrix has 3 rows and 4 columns, this is called a $3 × 4$ matrix.

In Python *numpy.array()* function is used to define a matrix, there is no  built-in type for matrices in Python. 

For example:

In [2]:
A = np.array([[3, 8, 5, 12], 
              [-5, 28, 3, 10],
              [-6, 2, 15, 3]
              ])
print("A =", A) 


A = [[ 3  8  5 12]
 [-5 28  3 10]
 [-6  2 15  3]]


In general, a $m × n$ matrix is shown as below

$ A =  \begin{bmatrix}
 a_{11}&a_{12}&a_{13}&...&a_{1n}\\
 a_{21}&a_{22}&a_{23}&...&a_{2n}\\
 a_{31}&a_{32}&a_{33}&...&a_{3n}\\
 ...&...&...&...&a_{4n}\\
 a_{m1}&a_{m2}&a_{m3}&...&a_{mn}
 \end{bmatrix} $

**Equality of Matrices**

The two matrices A and B are equal if: 1) the rows and columns of matrix A is same as that of matrix B, and 2) the elements of the matrix A should be equal to the corresponding elements of B.


Python provides some functions to check the equality of two matrices. *numpy.array_equal()* function returns True two matrices are the equal, and False if not.

In [3]:
A = np.array([[3, 8, 5, 12], 
              [-5, 28, 3, 10],
              [-6, 2, 15, 3]
              ])
B = np.array([[3, 8, 5, 12], 
              [-5, 28, 3, 10],
              [-6, 2, 15, 3]
              ])
print("A = B?", np.array_equal(A,B))

C = np.array([[2, 8, 5, 12], 
              [-5, 28, 3, 10],
              [-6, 2, 15, 3]
              ])
print("A = C?", np.array_equal(A,C))

A = B? True
A = C? False


Another Python function to check equality is *numpy.equal()*, it checks  element by element and gives the result of each element.

In [4]:
print("A = B?\n", np.equal(A,B))
print("\nA = C?\n", np.equal(A,C))

A = B?
 [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

A = C?
 [[False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In machine learning the matrices contain the calculated numbers, in most of cases it's difficult to get exact same matrices, instead, the two matrices are considered equal if they are close enough. *numpy.isclose()* function uses a tolerance limit to decide if two matrices are equal, if the differences between the elements less than the tolerance limit value, they are considered close enough and said to be equal.

Below example uses tolerance = 1e-2 to compare two matrices, the results are True for all elements. You can adjust the tolerance value to change the threshold to define how you consider they are equal.

In [5]:
A = np.array([[3.005, 8.492, 4.996, 12.001], 
              [-5.002, 27.993, 3.002, 10.0045],
              [-6.0034, 2.00012, 15.003, 2.9995]
              ])
B = np.array([[2.998, 8.5, 5.001, 11.997], 
              [-4.992, 28.0004, 3.0015, 9.9994],
              [-6.0023, 2.00045, 14.9996, 3.0001]
              ])
print(np.isclose(A,B,atol=1e-2))

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


## 1.2 Addition and Subtraction of Matrices

**Addition:**

$A + B =  \begin{bmatrix}
 a_{11}&a_{12}&...&a_{1n}\\
 a_{21}&a_{22}&...&a_{2n}\\
 ...&...&...&...\\
 a_{m1}&a_{m2}&...&a_{mn}
 \end{bmatrix} + 
\begin{bmatrix}
 b_{11}&b_{12}&...&b_{1n}\\
 b_{21}&b_{22}&...&b_{2n}\\
 ...&...&...&...\\
 b_{m1}&b_{m2}&...&b_{mn}
 \end{bmatrix} = 
\begin{bmatrix}
 a_{11}+b_{11}&a_{12}+b_{12}&...&a_{1n}+b_{1n}\\
 a_{21}+b_{21}&a_{22}+b_{22}&...&a_{2n}+b_{2n}\\
 ...&...&...&...\\
 a_{m1}+b_{m1}&a_{m2}+b_{m2}&...&a_{mn}+b_{mn}
 \end{bmatrix}$


**Subtraction:**

$ A - B =  \begin{bmatrix}
 a_{11}&a_{12}&...&a_{1n}\\
 a_{21}&a_{22}&...&a_{2n}\\
 ...&...&...&...\\
 a_{m1}&a_{m2}&...&a_{mn}
 \end{bmatrix} - 
\begin{bmatrix}
 b_{11}&b_{12}&...&b_{1n}\\
 b_{21}&b_{22}&...&b_{2n}\\
 ...&...&...&...\\
 b_{m1}&b_{m2}&...&b_{mn}
 \end{bmatrix} = 
\begin{bmatrix}
 a_{11}-b_{11}&a_{12}-b_{12}&...&a_{1n}-b_{1n}\\
 a_{21}-b_{21}&a_{22}-b_{22}&...&a_{2n}-b_{2n}\\
 ...&...&...&...\\
 a_{m1}-b_{m1}&a_{m2}-b_{m2}&...&a_{mn}-b_{mn}
 \end{bmatrix}$

Matrices A and B must be in the same size in order to perform addition and subtraction operations, there will be errors otherwise.

**Properties of Addition and Subtraction:**
1. Commutative Law: A + B = B + A
2. Associative Law:  (A + B) + C = A + (B + C)
3. Identity of the Matrix: A + O =  O + A = A, where O is zero matrix
4. Additive Inverse: A + (-A) = 0 = (-A) + A
5. A - B = A + (-B)

In Python, the numpy.add() is used for matrix addition and numpy.subtract() for subtraction.

For example:

In [6]:
A = np.array([[3, -1, 2], [-16, 2, -3]])
B = np.array([[8, 2, -8], [2, 1, 10]])
print ("A =\n", A) 
print ("\nB =\n", B) 
    
C = np.add(A, B) 
print ("\nC = A + B =\n", C) 

D = np.subtract(A, B) 
print ("\nD = A = B =\n", D) 

A =
 [[  3  -1   2]
 [-16   2  -3]]

B =
 [[ 8  2 -8]
 [ 2  1 10]]

C = A + B =
 [[ 11   1  -6]
 [-14   3   7]]

D = A = B =
 [[ -5  -3  10]
 [-18   1 -13]]


The two matrices must be in the same size to perform addition and subtraction, otherwise error will occur. Below example shows an error when doing addition for a 2 x 2 and 3 x 3 matrices.

In [7]:
A = np.array([[3, -1], [-16, 2]])
B = np.array([[8, 2, -8], [2, 1, 10]])
print ("A =\n", A) 
print ("\nB =\n", B) 

# Below two lines show an error when adding different size of matrix
# C = np.add(A, B) 
# print ("\nC = A + B =\n", C) 

A =
 [[  3  -1]
 [-16   2]]

B =
 [[ 8  2 -8]
 [ 2  1 10]]


**Scalar Addition and Subtraction**

The Addition and Subtraction can be performed between a matrix and a scalar (or a number), the result is the matrix with each item added to or subtracted by the scaler.

$C = k \pm A = k \pm  \begin{bmatrix}
 a_{11}&a_{12}&...&a_{1n}\\
 a_{21}&a_{22}&...&a_{2n}\\
 ...&...&...&...\\
 a_{m1}&a_{m2}&...&a_{mn}
 \end{bmatrix} = 
\begin{bmatrix}
 k \pm a_{11}&k \pm a_{12}&...&k \pm a_{1n}\\
 k \pm a_{21}&k \pm a_{22}&...&k \pm a_{2n}\\
 ...&...&...&...\\
 k \pm a_{m1}&k \pm a_{m2}&...&k \pm a_{mn}
 \end{bmatrix}
$

For example,  

In [8]:
A = np.array([[3, -1], [-16, 2]])
k = 5
print ("A =\n", A) 
print ("\nk =", k)

C = np.add(A, k)
print ("\nC = A + k =\n", C) 

D = np.subtract(A, k)
print ("\nD = A - k =\n", D) 

A =
 [[  3  -1]
 [-16   2]]

k = 5

C = A + k =
 [[  8   4]
 [-11   7]]

D = A - k =
 [[ -2  -6]
 [-21  -3]]


## 1.3 Multiplication of Matrices

Two matrices can be multiplied only when the number of columns in the first matrix equals to the number of rows in the second. I.e.

The first matrix is $m \times n$, and the second is $n × k$.

The resulting of the multiplication has the number of rows the same as the first matrix and the number of columns the same as the second matrix. I.e.

$(m \times n)(n \times k) = (m \times k)$

$\space$

In Python, the numpy.matmul() is used for matrix multiplication.
For example,

$\begin{bmatrix}
 3&-1&2\\
 -16&2&-3
 \end{bmatrix} \cdot
\begin{bmatrix}
 8&2&\\
 2&1\\
 3&2
 \end{bmatrix} = 
\begin{bmatrix}
 28&9\\
 -133&-36
 \end{bmatrix}$



The matrices multiplication involves dot products between rows of first matrix and columns of the second matrix. As shown below, the first step is the dot product between the first row of the first matrix and the first column of the second matrix. The result of this dot product is the element of resulting matrix at the first row and first column.

i.e. dot product of $\begin{bmatrix}
 3&-1&2\\
 \end{bmatrix} \cdot
\begin{bmatrix}
 8\\
 2\\
 3
 \end{bmatrix} = 3 \times 8 + (-1) \times 2 + 2 \times 3 = 28
$

Then the dot product between the same row of first matrix and the second column of the second matrix, and the result is positioned at first row and second column. 

i.e. dot product of $\begin{bmatrix}
 3&-1&2\\
 \end{bmatrix} \cdot
\begin{bmatrix}
 2\\
 1\\
 2
 \end{bmatrix} = 3 \times 2 + (-1) \times 1 + 2 \times 2 = 9
$

And so on.

<div>
<img src="https://raw.githubusercontent.com/jchen8000/MachineLearning/master/images/matrices_multiply.svg?token=GHSAT0AAAAAABT5MJMXQKOXQTB2CA6MCNU2YTISXCQ" width="480"/>
</div>

In [9]:
A = np.array([[3, -1, 2], [-16, 2, -3]])
B = np.array([[8, 2], [2, 1], [3, 2]])
print ("A(2x3) =\n", A) 
print ("\nB(3x2) =\n", B) 
    
C = np.matmul(A, B) 
print ("\nC(2x2) = A x B =\n", C) 

A(2x3) =
 [[  3  -1   2]
 [-16   2  -3]]

B(3x2) =
 [[8 2]
 [2 1]
 [3 2]]

C(2x2) = A x B =
 [[  28    9]
 [-133  -36]]


Sum of square can be calculated by dot product or multiplication for a vector.

$A =  \begin{bmatrix}
 a_{1}&a_{2}&...&a_{n}
 \end{bmatrix}$

$\begin{array}{rcl}
\displaystyle\sum_{i=1}^{n}a_i^2 & = & a_1^2 + a_2^2 +...+ a_n^2 \\
 & = & \begin{bmatrix}a_{1}&a_{2}&...&a_{n}\end{bmatrix} \cdot \begin{bmatrix}
 a_1\\ a_2\\ ...\\ a_n\end{bmatrix}\\
 & = & A \cdot A^T
\end{array}$

Either *np.dot()* or *np.matmul()* can be used for this purpose.

In [10]:
A = np.array([3, -1, 2, -6, 2, -3])
B = np.array([1,  2, 3, 2, -1, 5])
print("Sum of square:", np.matmul(A, np.transpose(A)) )
print("Sum of multiply:", np.dot(A, np.transpose(B)) )

Sum of square: 63
Sum of multiply: -22



$\space$

In general, 

$ C_{m \times k} = A_{m \times n} \cdot B_{n \times k} =  \begin{bmatrix}
 a_{11}&a_{12}&...&a_{1n}\\
 a_{21}&a_{22}&...&a_{2n}\\
 ...&...&...&...\\
 a_{m1}&a_{m2}&...&a_{mn}
 \end{bmatrix} \cdot
\begin{bmatrix}
 b_{11}&b_{12}&...&b_{1k}\\
 b_{21}&b_{22}&...&b_{2k}\\
 ...&...&...&...\\
 b_{n1}&b_{n2}&...&b_{nk}
 \end{bmatrix} = 
\begin{bmatrix}
 c_{11}&a_{12}&...&c_{1k}\\
 c_{21}&a_{22}&...&c_{2k}\\
 ...&...&...&...\\
 c_{m1}&c_{m2}&...&c_{mk}
 \end{bmatrix}$

where 
 
$c_{ij} = a_{i1}  b_{1j} + a_{i2}b_{2j} + a_{i3}b_{3j} + ... + a_{in}b_{nj}$


$\space$

**Properties of Matrix Multiplication**

1. $(AB)C = A(BC)$
2. $AB \neq BA$
3. $A(B+C) = AB + AC$
4. $(A+B)C = AC + BC$

**Scalar Multiplication**

Similar to scalar addition, the matrix can be multiplied by a scalar number, the resulting matrix is same size as the original matrix, and each element of the matrix is multiplied by the scalar.

$C = \lambda A = \lambda \begin{bmatrix}
 a_{11}&a_{12}&...&a_{1n}\\
 a_{21}&a_{22}&...&a_{2n}\\
 ...&...&...&...\\
 a_{m1}&a_{m2}&...&a_{mn}
 \end{bmatrix} = 
\begin{bmatrix}
 \lambda a_{11}&\lambda a_{12}&...&\lambda a_{1n}\\
 \lambda a_{21}&\lambda a_{22}&...&\lambda a_{2n}\\
 ...&...&...&...\\
 \lambda a_{m1}&\lambda a_{m2}&...&\lambda a_{mn}
 \end{bmatrix}$

In Python, for example,

In [11]:
A = np.array([[3, -1, 2], [-16, 2, -3]])
k = 3
print ("A =\n", A) 
print ("\nk =", k) 
    
C = k * A 
print ("\nC = k * A =\n", C) 

A =
 [[  3  -1   2]
 [-16   2  -3]]

k = 3

C = k * A =
 [[  9  -3   6]
 [-48   6  -9]]


## 1.4 Identity Matrix and Inverse of Matrices

**What is an identity matrix?**

An identity matrix is a square matrix where its diagonal elements have the value of one, while the rest of the matrix elements are zero.

$I = 
\begin{bmatrix}
 1&0&\cdots&0\\
 0&1&\cdots&0\\
 \cdots&\cdots&\cdots&\cdots \\
 0&0&\cdots&1\\
 \end{bmatrix} $

In Python, *numpy.identity()* function is used to initialize an identity matrix. 

E.g. below code defines a 5 x 5 identity matrix:

In [12]:
I = np.identity(5)
print("I=\n", I)

I=
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**What is the Inverse of a Matrix?**

The inverse of a matrix $A$, also called a reciprocal matrix, is a matrix denoted as $A^{-1}$, such as a reciprocal of number 5 is $\frac{1}{5}$.

A number multiplied by its reciprocal gets result of 1, 

$5 \cdot \frac{1}{5} = 1$

Similarly, a matrix multiplied by its inverse gets identity matrix,

$A \cdot A^{-1} = I$

Hopefully this explains the inverse of a matrix. It's complicated to calculate the inverse, and sometimes there is no inverse for some matrices. We do not introduce the methods to calculate it. Fortunately Python provide function numpy.linalg.inv() to calculate inverse.

For example:

In [13]:
A = np.array([[3, -1, 2], [-16, 2, -3], [8, 1, 6]])
A_1 = np.linalg.inv(A)
I = np.matmul(A, A_1) 
print("A=\n", A)
print("\nInverse of A_1 = \n", A_1)
print("\nA multiply by A_1:\n", I)

print("\nCheck A multiply by A_1 with Identity:\n", np.isclose(I,np.identity(3)))

A=
 [[  3  -1   2]
 [-16   2  -3]
 [  8   1   6]]

Inverse of A_1 = 
 [[-0.16483516 -0.08791209  0.01098901]
 [-0.79120879 -0.02197802  0.25274725]
 [ 0.35164835  0.12087912  0.10989011]]

A multiply by A_1:
 [[ 1.00000000e+00  5.55111512e-17  2.77555756e-17]
 [ 1.66533454e-16  1.00000000e+00  1.38777878e-17]
 [-3.33066907e-16  0.00000000e+00  1.00000000e+00]]

Check A multiply by A_1 with Identity:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


There is no concept of matrix division, however the inverse can by used for this purpose. For example there is:

$XA = B$

We know $A$ and $B$, and want to find $X$

First, multiply both sides by $A^{-1}$

$XAA^{-1} = BA^{-1}$

$XI = BA^{-1}$

Because $XI = X$, so finally:

$X = BA^{-1}$

## 1.5 Matrix Transpose

The transpose of matrix $A$ is denoted as $A^T$, and simply switches its rows with columns. 

In Python, *numpy.transpose()* is used for transpose.

In [14]:
A = np.array([[3, -1, 2], [-16, 2, -3]])
A_t = np.transpose(A)
print("A=\n", A)
print("\nTranspose = \n", A_t)

A=
 [[  3  -1   2]
 [-16   2  -3]]

Transpose = 
 [[  3 -16]
 [ -1   2]
 [  2  -3]]


## 1.6 Matrix Determinant

The determinant is a number that can be calculated from a square matrix. The matrix must be square which means it has the same number of rows as columns. It's denoted as:

$det(A) = \left| A \right| = \begin{vmatrix}
 a_{11}&a_{12}&...&a_{1n}\\
 a_{21}&a_{22}&...&a_{2n}\\
 ...&...&...&...\\
 a_{n1}&a_{n2}&...&a_{nn}
 \end{vmatrix}$

$\space$

 **How to calculate the determinant?**

 Let's begin with an example of 2 x 2 matrix:

$det(A) = \left| A \right| = 
\begin{vmatrix}
 3&-1\\
 5&2\\
\end{vmatrix} = 3 \times 2 - (-1) \times 5 = 11$

*numpy.linalg.det()* function is provided for calculating determinant.

In [15]:
A = np.array([[3, -1], [5, 2]])
A_det = np.linalg.det(A)
print("A=\n", A)
print("\nDeterminant = \n", A_det)

A=
 [[ 3 -1]
 [ 5  2]]

Determinant = 
 11.000000000000002


Calculate the determinant for a 3 x 3 matrix,

$det(A) = \left| A \right| = 
\begin{vmatrix}
 3&-1&2\\
 -16&2&-3\\
 8&1&6\\
\end{vmatrix}= 3 \begin{vmatrix}
 2&-3\\
 1&6\\
\end{vmatrix} - (-1) \begin{vmatrix}
 -16&-3\\
 8&6\\
\end{vmatrix} + 2 \begin{vmatrix}
 -16&2\\
 8&1\\
\end{vmatrix}$

$ = 3 × 15 - (-1) × (-72) + 2 \times (-32) = -91$

$\space$

Again, use numpy.linalg.det() to calculate it:


In [16]:
A = np.array([[3, -1, 2], [-16, 2, -3], [8, 1, 6]])
A_det = np.linalg.det(A)
print("A=\n", A)
print("\nDeterminant = \n", A_det)

A=
 [[  3  -1   2]
 [-16   2  -3]
 [  8   1   6]]

Determinant = 
 -90.99999999999997


## 1.7 Eigenvectors/Eigenvalues and Singular Value Decomposition (SVD)

**Eigenvectors and Eigenvalues**

There is a square matrix A, a scaler $\lambda$ and a non-zero vector $\vec{v}$, they satisfy the following relation,

$A \vec{v} = \lambda \vec{v}$

Then $\lambda$ is **Eigenvalue** and $\vec{v}$ is **Eigenvector** of Matrix $A$.

In [17]:
import numpy as np

a = np.array([[3, 1], [2, 2]])
eigenvalue, eigenvector = np.linalg.eig(a)

print("Eigenvalue = ", eigenvalue)
print("Eigenvector = \n", eigenvector)


Eigenvalue =  [4. 1.]
Eigenvector = 
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


w is the eigenvalue which has two number means there are two eigenvalues for the matrix; v is the eigenvector, its first column is the first eigenvector, and its second column is the second eigenvector.

To verify the $A \vec{v} = \lambda \vec{v}$ relationship:

In [18]:
print("Verify first eigenvector:", np.allclose(np.dot(a,eigenvector[:,0]),np.dot(eigenvalue[0],eigenvector[:,0])))
print("Verify second eigenvector:", np.allclose(np.dot(a,eigenvector[:,1]),np.dot(eigenvalue[1],eigenvector[:,1])))

Verify first eigenvector: True
Verify second eigenvector: True


The eigenvectors returned by this function are normalized, below is to verify they are normalized by printing the norm of each eigenvector.

In [19]:
print("norm of first eigenvector:", np.linalg.norm(eigenvector[:,0]))
print("norm of second eigenvector:", np.linalg.norm(eigenvector[:,1]))

norm of first eigenvector: 0.9999999999999999
norm of second eigenvector: 0.9999999999999999


**Singular Value Decomposition (SVD)**
A matrix can be factorized as three matrices, it's denoted as:

$A = U Σ V^T$

The SVD has some algebraic properties and a lot of applications in data science and machine learning. Here we do not deep-dive into math details and not prove it from math perspective. We will introduce how to use Python to calculate it.

$A$ is $m \times n$ matrix,

$U$ is $m \times m$ orthogonal matrix,

$\Sigma$ is $m \times n$ diagonal matrix, the singular values are in its diagonal, and all others are zero.

$V$ is $n \times n$ orthogonal matrix.

$\space$

$U$ and $V$ are orthogonal matrices means:

$U^TU = I_{m\times m}$ and $V^TV = I_{n\times n}$ 



Singular Value Decomposition (SVD) with Python scipy package. 
And reconstruct the original matrix.

In [20]:
from scipy.linalg import svd

A = np.array([[1, 2], [3, 4], [5, 6]])
print("A=\n", A)
# SVD
U, s, VT = svd(A)
sigma = np.zeros((A.shape[0], A.shape[1]))
sigma[:A.shape[1], :A.shape[1]] = np.diag(s)
print("\nU=\n", U)
print("\nSigma=\n", sigma)
print("\nV^T=\n", VT)

A=
 [[1 2]
 [3 4]
 [5 6]]

U=
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

Sigma=
 [[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]

V^T=
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [21]:
A_1 = (U.dot(sigma)).dot(VT)
print("Re-construct A from SVD:\n", A_1)

Re-construct A from SVD:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]


References:

1. https://www.tntech.edu/cas/pdf/math/techreports/TR-2018-2.pdf
2. http://www.cs.toronto.edu/~jepson/csc420/notes/introSVD.pdf
3. https://www.cs.cmu.edu/~venkatg/teaching/CStheory-infoage/book-chapter-4.pdf


## 1.8 Rank of Matrices

The rank of a matrix describes the Linear Dependence between its rows or columns. If a row in matrix is made of other rows by multiplying a scaler, then that row is dependent on other rows and not count towards the rank. 

For example:

$A = \begin{bmatrix}
 3&-1&2\\
 6&-2&4
 \end{bmatrix} $

The numbers in second row are made of the first row by multiplying 2. So the rank of this matrix is 1 not 2.

Look at the columns of this matrix, the second column is made of first column by multiplying $-\frac{1}{3}$, and the third column is also made of first column by multiplying $\frac{2}{3}$. So from the columns the rank is also 1.

$\space$

Rank is calculated by *numpy.linalg.matrix_rank()* function.

In [22]:
a = np.array([[3,-1,2], [6,-2,4]])
rank = np.linalg.matrix_rank(a)
print('A = \n', a)
print('\nRank of A = ',rank)

A = 
 [[ 3 -1  2]
 [ 6 -2  4]]

Rank of A =  1


In [23]:
I = np.identity(4)
print('I = \n', I)
print('\nRank = ',np.linalg.matrix_rank(I))

I = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Rank =  4
